### ISSUE TITLE
CSS zoneerder verplaatsen

### ISSUE THREAD

**Issue by JonasGe** [OnroerendErfgoed/oerelia#102]
Momenteel worden die classes globaal toegepast waardoor ongewenste CSS toegepast wordt zoals dit:

https://github.com/OnroerendErfgoed/openbare_onderzoeken/issues/1173

**Comment by cedrikv** [comment]
scope eerder dan css rules specifieker maken?

**Comment by JonasGe** [comment]
Ja, op 1 plaats is het de CSS verplaatsen naar binnen de zoneerder component maar op andere plaatsen (steekt op 5 plaatsen) is het wat meer aanpassing.
