### ISSUE TITLE
Autocomplete resultaat bij aanklikken van suggestie

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#139]
Momenteel klikken we op een suggestie en dan moeten we nog is op een knop duwen om de suggestie als resultaat toe te voegen. Ze willen nu dat we de knop voor het toevoegen weglaten en dat het resultaat er direct komt na het klikken op een suggestie. 

![image.png](https://images.zenhubusercontent.com/5d88b68d09acc20001fc6776/99262336-6b80-4b7f-99d8-2bf5c5437ee0)

![image.png](https://images.zenhubusercontent.com/5d88b68d09acc20001fc6776/1b17e759-da10-4b7a-b009-57d142fb22ce)

**Comment by cedrikv** [comment]
Die hadden we al eens ergens aangepast ook, lijkt me inderdaad beter.

**Comment by yannickkuypers** [comment]
Kheb dit kunnen oplossen door valueChanged listeners te zetten op de values van de autocomplete. Hiervoor moeten we dus niets aanpassen in die autocomplete component van oerelia dus das beter. Kga het ticketje gewoon dichtdoen aangezien dit overbodig is nu.
