### ISSUE TITLE
multi-select component met value lijst en trash icons

### ISSUE THREAD

**Issue by roefem** [OnroerendErfgoed/oerelia#159]
![image](https://user-images.githubusercontent.com/1849458/155356076-ac87eb4f-d988-49a4-81df-47989e29e649.png)

**Comment by cedrikv** [comment]
@roefem nu is de linker border van de select weg, die zou ik er proberen wel te zetten

**Comment by roefem** [comment]
> @roefem nu is de linker border van de select weg, die zou ik er proberen wel te zetten

Ben je zeker dat die linker border nodig is? bij andere inputs is die er ook niet:
![image](https://user-images.githubusercontent.com/62388265/155361479-e971fa68-c405-4fbb-a6aa-b999b532e91b.png)

**Comment by cedrikv** [comment]
ok, we zullen het zo laten
