### ISSUE TITLE
Zoneerder zone wordt niet hertekend

### ISSUE THREAD

**Issue by roefem** [OnroerendErfgoed/oerelia#171]
De zone wordt niet hertekend in olMap.ts wanneer deze aangepast wordt in het parent component

**Comment by cedrikv** [comment]
geraakt er geen loop van triggers aan de gang zo? zegt mij heel vaagweg iets, dat we daarmee in de dojo versie problemen gehad hebben

**Comment by roefem** [comment]
> geraakt er geen loop van triggers aan de gang zo? zegt mij heel vaagweg iets, dat we daarmee in de dojo versie problemen gehad hebben
Lijkt zich te gedragen, de onChange triggert enkel wanneer de zone variabele herassigned wordt
