### ISSUE TITLE
images paden uit pyoes gebruiken met default

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#197]
Voor https://github.com/OnroerendErfgoed/oerelia/pull/192 gebruiken we paths in de css die naar images verwijzen. Die verwijzen nu naar een path in de parent applicatie wat eigenlijk niet de bedoeling zou mogen zijn. 

Doel: proberen op te lossen zodat we de image in de component zelf hebben zodat die img altijd beschikbaar is.
![image](https://user-images.githubusercontent.com/9083121/176387688-0bc74bdc-79c1-4dfe-8908-e7e6fc0267f3.png)

https://aurelia.io/docs/cli/cli-bundler/basics#copy-other-files-eg-fonts

**Comment by cedrikv** [comment]
ik weet niet zeker dat dat een probleem is. momenteel zijn onze layout en code gescheiden. code in oerelia en layout in pyoes. ooit mergen we die wss, maar momenteel dus gescheiden houden.

**Comment by yannickkuypers** [comment]
De reden waarom ik dat ook wil doen is omdat we nu een hardcoded variable in die beheer-header.scss hebben zitten. En die moet er zijn want anders build het au-plugin command niet. Gevolg daarvan is dan dat uw image in uw parent applicatie altijd in die static > img > pyoes map moet zitten dus daar hebben we weinig flexibiliteit mee dan.

**Comment by cedrikv** [comment]
en de var een default waarde geven, en dan laten overriden door pyoes settings gaat niet?

**Comment by cedrikv** [comment]
ok voor mij om image mee in de component te bewaren
