### ISSUE TITLE
Beheer header/footer updaten

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#206]
Momenteel geeft inventaris errors bij de build in app omdat de images in beheer header/footer niet gevonden kunnen worden. 
Zien dat we deze images altijd kunnen vinden.

**Comment by cedrikv** [comment]
is dez niet hetzelfe als #197

**Comment by yannickkuypers** [comment]
Hmmm met wat extra's denk ik ja. Maar kzal die #197 ervoor gebruiken dan.
