### ISSUE TITLE
Bugfix koppeling-dialog

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#222]
Titel staat niet goed

![image.png](https://images.zenhubusercontent.com/5d88b68d09acc20001fc6776/66468436-cef8-4cef-83bf-bf9b52ea66a3)

**Comment by cedrikv** [comment]
![image](https://user-images.githubusercontent.com/1849458/187399013-b7b5eba5-42fb-4799-a1b9-5480f30e2601.png)
dat lijk niet ok
