### ISSUE TITLE
UNESCO en vast_la toevoegen aan Zoneerder layerconfig

### ISSUE THREAD

**Issue by JonasGe** [OnroerendErfgoed/oerelia#223]
- UNESCO (kern en buffer, https://github.com/OnroerendErfgoed/geoportaal/blob/87e0c36e283e912e41c47726de23315b228966ad/geoportaal/static/apps/src/models/layer.ts#L454-L467) toevoegen aan layerconfig (@cedrikv onder `bes` zodat de laag altijd meekomt of onder een aparte layer zodat die default uitgezet kan worden?)
- Eens testen of de layerconfig (meer specifiek overlays.bes.wmsLayers) aangepast kan worden in een ander project (om bvb een layer toe te voegen aan de wmsLayers string).

**Comment by cedrikv** [comment]
alleszins optioneel maken en default uit voor backwards compability?
