### ISSUE TITLE
Systemfields component updated aanpassen

### ISSUE THREAD

**Issue by JonasGe** [OnroerendErfgoed/oerelia#250]
https://github.com/OnroerendErfgoed/oerelia/blob/master/src/systemfields/systemfields.ts

Bij tussentijds ingediende dingen bestaan die updatedAt en updatedBy nog niet. Dit geeft een invalid date voor de eerste en gewoon niks voor het tweede.

Dus best die updated lijn weglaten als die values nog niet bestaan.

**Comment by JonasGe** [comment]
@JolijnL @astridvanhumbeeck of is er ooit iets anders afgesproken?

**Comment by astridvanhumbeeck** [comment]
Ik denk niet dat het ooit anders is afgesproken, denk dat het er nu vaak staat met vraagtekens of invalid. Dus zeker goed als we dat kunnen verbergen zolang er geen waarde is.
