### ISSUE TITLE
Fix kaart achtergronden in zoneerder

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#299]
Door de upgrade van AGIV services werken bepaalde layers niet meer. Fixen van ortho layer en de skyview/hillshade

![image.png](https://images.zenhubusercontent.com/5d88b68d09acc20001fc6776/3af951ec-70c9-467b-b8a2-15eb0296cd30)

**Comment by cedrikv** [comment]
refs #287
