### ISSUE TITLE
GRB referentielaag: Basic GUI

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#411]

**Comment by roefem** [comment]
De wms legende voor  de gebouwen laag heeft meerdere kleuren, hieronder mogelijke voorstellen om dit mooi weer te geven in de zoneerder component:
voorstel 1:
![image](https://github.com/user-attachments/assets/128895e0-1bd8-4c1f-b869-c2520b90cb71)

**Comment by goessebr** [comment]
Net even besproken met @astridvanhumbeeck 

Wij zijn voorstander van voorstel 1 omdat de gebruiker bij voorstel 2 vragen zal stellen waarom daar verschillende kleurcodes staan en wat dan voor welke definitie staat.

Een nice to have indien niet veel extra werk zou kunnen zijn om:
- voorstel 2 te hebben bij het openen, maar waarbij er een pijltje is om de optie open te klappen, zodat je de extra informatie pas te zien krijgt wanneer je op het pijltje klikt
- als je op het pijltje klikt krijg je dan de equivalent van voorstel 1. We tonen daar ook wel een pijltje om de extra informatie terug dicht te klappen

Dus een combinatie van voorstel 1 en 2 waar we van beide het beste behouden. Maar op zich is voorstel 1 goed. Tenzij jullie denken dat die combinatie haalbaar is zonder al te veel extra werk.
