### ISSUE TITLE
Zoneerder: Als beheerder wil ik snel de WKT van mijn zone kunnen kopiëren naar mijn plakbord

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oerelia#466]
Komt uit https://trac.onroerenderfgoed.be/toepassingen/ticket/7630

![image](https://github.com/user-attachments/assets/796a6aa2-1e31-42ea-8a9d-a0b5cf6fa1b5)

Zie screenshot als startbasis. Naast het vuilbakje komt er een copy-icon. Als je klikt op het copy-icon zal de WKT van die zone worden opgenomen in het plakbord.

**Comment by cedrikv** [comment]
jama, ge moogt geen tickets terug open doen dat al in vorige release zitten hé, dan moede bugticketje maken. beetje de kantjes aflopen ofzo
