### ISSUE TITLE
Uitbreiden zoneerder component met knoppen

### ISSUE THREAD

**Issue by yannickkuypers** [OnroerendErfgoed/oerelia#54]
ter referentie van https://github.com/OnroerendErfgoed/proces_toelatingen_beschermd_erfgoed/issues/32 willen we knoppen kunnen zetten in de zoneerder component.

**Comment by cedrikv** [comment]
@yannickkuypers  kan je nog oplijsten welke knoppen juist? een screenshot met de huidige situatie tov van waar we naartoe willen zou ook al helpen

**Comment by yannickkuypers** [comment]
**Zonder knoppen**
![image](https://user-images.githubusercontent.com/9083121/83511275-af54a600-a4ce-11ea-8e59-c98c26cb6577.png)

**Met knoppen** 
![image](https://user-images.githubusercontent.com/9083121/83511229-a06df380-a4ce-11ea-9051-2249edef00d4.png)
