### ISSUE TITLE
DHM lagen als achtergrondlagen toevoegen

### ISSUE THREAD

**Issue by goessebr** [OnroerendErfgoed/oerelia#95]
Komt uit https://github.com/OnroerendErfgoed/inventaris/issues/4091

Kunnen we de DHM lagen als achtergrondlagen toevoegen?

@OnroerendErfgoed/applicatiebeheerders

**Comment by cedrikv** [comment]
gefixed in https://github.com/OnroerendErfgoed/oerelia/issues/123
